import { LifecycleStep } from '../model/types.ts';

export function createCompositeLifecycleSteps(
  resourceCount = 4,
  depName = 'app-deployment',
  svcName = 'app-service',
  ingName = 'app-ingress',
): LifecycleStep[] {
  return [
    {
      stepNumber: 1,
      title: `kubectl submits multi-document manifest (${resourceCount} resources)`,
      sourceNodeId: 'node-user',
      targetNodeId: 'node-kubectl',
      edgeId: 'edge-user-kubectl',
      edgeLabel: 'kubectl apply -f manifest.yaml',
      what: `The developer applies a unified multi-document YAML containing ${resourceCount} interrelated Kubernetes resources.`,
      why: 'Multi-document manifests declare full-stack application architectures in a single atomic transaction.',
      componentName: 'kubectl',
      componentRole: 'CLI client parsing and submitting multi-resource documents.',
      docsUrl: 'https://kubernetes.io/docs/concepts/cluster-administration/manage-deployment/',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-user': 'success',
        'node-kubectl': 'active',
      },
      edgeStatusUpdates: {
        'edge-user-kubectl': 'active',
      },
    },
    {
      stepNumber: 2,
      title: 'API Server validates and stores all resources in etcd',
      sourceNodeId: 'node-kubectl',
      targetNodeId: 'node-apiserver',
      edgeId: 'edge-kubectl-apiserver',
      edgeLabel: `POST ${resourceCount} resources`,
      what: 'The API Server validates every object schema in parallel and commits the resource records to etcd.',
      why: 'Centralized validation prevents partial or corrupted configurations from entering cluster state.',
      componentName: 'kube-apiserver',
      componentRole: 'Validates and persists all incoming API objects.',
      docsUrl: 'https://kubernetes.io/docs/concepts/overview/components/#kube-apiserver',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-kubectl': 'success',
        'node-apiserver': 'active',
        'node-etcd': 'active',
      },
      edgeStatusUpdates: {
        'edge-user-kubectl': 'complete',
        'edge-kubectl-apiserver': 'active',
        'edge-apiserver-etcd': 'active',
      },
    },
    {
      stepNumber: 3,
      title: 'Configuration and Secrets registered in namespace',
      sourceNodeId: 'node-apiserver',
      targetNodeId: 'node-etcd',
      edgeId: 'edge-apiserver-etcd',
      edgeLabel: 'Register ConfigMap & Secret objects',
      what: 'ConfigMaps and Secrets are registered in the namespace catalog, ready for container injection.',
      why: 'Workload pods require configuration data before container startup can begin.',
      componentName: 'Namespace Catalog',
      componentRole: 'Maintains isolated namespace objects.',
      docsUrl: 'https://kubernetes.io/docs/concepts/configuration/configmap/',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-etcd': 'success',
        'node-apiserver': 'active',
      },
      edgeStatusUpdates: {
        'edge-kubectl-apiserver': 'complete',
        'edge-apiserver-etcd': 'complete',
      },
    },
    {
      stepNumber: 4,
      title: 'Deployment Controller creates ReplicaSet',
      sourceNodeId: 'node-controllermanager',
      targetNodeId: 'node-apiserver',
      edgeId: 'edge-cm-create-pods',
      edgeLabel: `Deployment -> Create ReplicaSet`,
      what: 'The Deployment Controller detects the Deployment and provisions a new ReplicaSet with the desired replica specification.',
      why: 'ReplicaSets handle discrete pod counts while Deployments manage version rollouts.',
      componentName: 'kube-controller-manager',
      componentRole: 'Runs core reconciliation loops.',
      docsUrl: 'https://kubernetes.io/docs/concepts/workloads/controllers/deployment/',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-controllermanager': 'active',
        'node-apiserver': 'active',
      },
      edgeStatusUpdates: {
        'edge-cm-create-pods': 'active',
      },
    },
    {
      stepNumber: 5,
      title: 'ReplicaSet Controller creates workload Pods',
      sourceNodeId: 'node-controllermanager',
      targetNodeId: 'node-apiserver',
      edgeId: 'edge-cm-create-pods',
      edgeLabel: 'Create 2 Pod definitions',
      what: 'The ReplicaSet Controller requests creation of 2 pods configured with the container images and volume references.',
      why: 'Maintains the exact number of declared pod instances.',
      componentName: 'ReplicaSet Controller',
      componentRole: 'Creates and monitors pod instances.',
      docsUrl: 'https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-controllermanager': 'active',
        [`node-pod-${depName}-1`]: 'warning',
        [`node-pod-${depName}-2`]: 'warning',
      },
      edgeStatusUpdates: {
        'edge-cm-create-pods': 'active',
      },
    },
    {
      stepNumber: 6,
      title: 'Scheduler binds Pods across Worker Nodes',
      sourceNodeId: 'node-scheduler',
      targetNodeId: 'node-apiserver',
      edgeId: 'edge-scheduler-assign',
      edgeLabel: 'Assign: Pod 1 -> Node 1, Pod 2 -> Node 2',
      what: 'The scheduler balances the pods across Worker Node 1 and Worker Node 2 to ensure high availability.',
      why: 'Multi-node spreading protects applications against single-node hardware failures.',
      componentName: 'kube-scheduler',
      componentRole: 'Assigns unscheduled pods to optimal nodes.',
      docsUrl: 'https://kubernetes.io/docs/concepts/scheduling-eviction/kube-scheduler/',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-scheduler': 'success',
        'node-apiserver': 'active',
      },
      edgeStatusUpdates: {
        'edge-cm-create-pods': 'complete',
        'edge-scheduler-assign': 'active',
      },
    },
    {
      stepNumber: 7,
      title: 'Kubelets pull images and mount configuration',
      sourceNodeId: 'node-kubelet-1',
      targetNodeId: `node-pod-${depName}-1`,
      edgeId: 'edge-kubelet-start-1',
      edgeLabel: 'Mount ConfigMap/Secret & pull container image',
      what: 'Kubelets fetch container images and bind-mount configuration files into the container execution environments.',
      why: 'Containers receive configuration and secrets directly upon boot.',
      componentName: 'kubelet',
      componentRole: 'Manages node container lifecycle.',
      docsUrl: 'https://kubernetes.io/docs/concepts/overview/components/#kubelet',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-kubelet-1': 'active',
        'node-kubelet-2': 'active',
      },
      edgeStatusUpdates: {
        'edge-scheduler-assign': 'complete',
        'edge-kubelet-start-1': 'active',
        'edge-kubelet-start-2': 'active',
      },
    },
    {
      stepNumber: 8,
      title: 'Workload Pods start and enter Running phase',
      sourceNodeId: 'node-kubelet-1',
      targetNodeId: `node-pod-${depName}-1`,
      edgeId: 'edge-kubelet-start-1',
      edgeLabel: 'Containers running & healthy',
      what: 'All containers initialize successfully and pass readiness probes. Kubelets report pod status as Running.',
      why: 'Readiness indicates that the pods can now receive client network traffic.',
      componentName: 'Pod Workloads',
      componentRole: 'Running application pods.',
      docsUrl: 'https://kubernetes.io/docs/concepts/workloads/pods/',
      durationMs: 2000,
      nodeStatusUpdates: {
        [`node-pod-${depName}-1`]: 'success',
        [`node-pod-${depName}-2`]: 'success',
        'node-kubelet-1': 'success',
        'node-kubelet-2': 'success',
      },
      edgeStatusUpdates: {
        'edge-kubelet-start-1': 'complete',
        'edge-kubelet-start-2': 'complete',
      },
    },
    {
      stepNumber: 9,
      title: 'Service matches Deployment Pod labels',
      sourceNodeId: `node-service-${svcName}`,
      targetNodeId: `node-pod-${depName}-1`,
      edgeId: 'edge-service-pods',
      edgeLabel: 'Match labels & generate EndpointSlice',
      what: `The Service selector matches labels on the running Deployment pods and registers their IPs in the EndpointSlice.`,
      why: 'Establishes the internal load balancing cluster endpoint.',
      componentName: 'Service & EndpointSlice',
      componentRole: 'Maintains backend endpoints for dynamic workloads.',
      docsUrl: 'https://kubernetes.io/docs/concepts/services-networking/service/',
      durationMs: 2000,
      nodeStatusUpdates: {
        [`node-service-${svcName}`]: 'active',
      },
      edgeStatusUpdates: {
        'edge-service-pods': 'active',
      },
    },
    {
      stepNumber: 10,
      title: 'kube-proxy programs iptables packet forwarding',
      sourceNodeId: 'node-kubeproxy-1',
      targetNodeId: `node-pod-${depName}-1`,
      edgeId: 'edge-service-pods',
      edgeLabel: 'iptables DNAT rules synchronized',
      what: 'kube-proxy updates local kernel packet filters so cluster traffic to the Service IP distributes across the backend pods.',
      why: 'Enables high-performance East-West cluster routing.',
      componentName: 'kube-proxy',
      componentRole: 'Programs Linux kernel networking rules.',
      docsUrl: 'https://kubernetes.io/docs/concepts/overview/components/#kube-proxy',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-kubeproxy-1': 'success',
        'node-kubeproxy-2': 'success',
        [`node-service-${svcName}`]: 'success',
      },
      edgeStatusUpdates: {
        'edge-service-pods': 'complete',
      },
    },
    {
      stepNumber: 11,
      title: 'Ingress Controller updates reverse proxy routes',
      sourceNodeId: 'node-ingress-controller',
      targetNodeId: `node-ingress-${ingName}`,
      edgeId: 'edge-ingress-service',
      edgeLabel: `Configure routes: / -> ${svcName}:80`,
      what: `The Ingress Controller reads the Ingress host and path rules and updates upstream proxy targets to point to the Service endpoints.`,
      why: 'Exposes the internal cluster service to public internet traffic.',
      componentName: 'Ingress Controller',
      componentRole: 'Edge load balancer proxying external HTTP traffic.',
      docsUrl: 'https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-ingress-controller': 'success',
        [`node-ingress-${ingName}`]: 'success',
      },
      edgeStatusUpdates: {
        'edge-ingress-service': 'active',
      },
    },
    {
      stepNumber: 12,
      title: 'Full-stack application is live and receiving traffic',
      sourceNodeId: 'node-user',
      targetNodeId: 'node-ingress-controller',
      edgeId: 'edge-ingress-service',
      edgeLabel: 'End-to-end routing active: Ingress -> Service -> Pod',
      what: 'The entire stack is operational. Traffic flows from Ingress through Service load balancers directly to configured pods.',
      why: 'Completes the multi-resource Kubernetes application deployment lifecycle.',
      componentName: 'Kubernetes Application Stack',
      componentRole: 'Fully configured and verified multi-resource application.',
      docsUrl: 'https://kubernetes.io/docs/home/',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-user': 'success',
        'node-ingress-controller': 'success',
        [`node-service-${svcName}`]: 'success',
        [`node-pod-${depName}-1`]: 'success',
        [`node-pod-${depName}-2`]: 'success',
      },
      edgeStatusUpdates: {
        'edge-ingress-service': 'complete',
      },
    },
  ];
}
