import { LifecycleStep } from '../model/types.ts';

export function createDeploymentLifecycleSteps(
  deploymentName = 'frontend-deployment',
  replicas = 3,
): LifecycleStep[] {
  return [
    {
      stepNumber: 1,
      title: 'kubectl submits Deployment manifest',
      sourceNodeId: 'node-user',
      targetNodeId: 'node-kubectl',
      edgeId: 'edge-user-kubectl',
      edgeLabel: `kubectl apply -f ${deploymentName}.yaml`,
      what: 'The developer runs kubectl apply with the Deployment manifest. kubectl parses the YAML and submits a POST request to the API Server.',
      why: 'kubectl initiates declarative management of the multi-replica workload.',
      componentName: 'kubectl',
      componentRole: 'Command-line tool for communicating with the cluster API server.',
      docsUrl: 'https://kubernetes.io/docs/concepts/workloads/controllers/deployment/',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-user': 'success',
        'node-kubectl': 'active',
      },
      edgeStatusUpdates: {
        'edge-user-kubectl': 'active',
      },
    },
    {
      stepNumber: 2,
      title: 'API Server validates and stores Deployment',
      sourceNodeId: 'node-kubectl',
      targetNodeId: 'node-apiserver',
      edgeId: 'edge-kubectl-apiserver',
      edgeLabel: 'POST /apis/apps/v1/deployments',
      what: 'The API Server authenticates the user, executes admission webhooks, and writes the Deployment object to etcd.',
      why: 'The API Server acts as the gatekeeper ensuring schema compliance and persisting desired state.',
      componentName: 'kube-apiserver',
      componentRole: 'Validates and configures data for API objects including Deployments.',
      docsUrl: 'https://kubernetes.io/docs/concepts/overview/components/#kube-apiserver',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-kubectl': 'success',
        'node-apiserver': 'active',
        'node-etcd': 'active',
      },
      edgeStatusUpdates: {
        'edge-user-kubectl': 'complete',
        'edge-kubectl-apiserver': 'active',
        'edge-apiserver-etcd': 'active',
      },
    },
    {
      stepNumber: 3,
      title: 'Deployment Controller detects new Deployment',
      sourceNodeId: 'node-controllermanager',
      targetNodeId: 'node-apiserver',
      edgeId: 'edge-cm-apiserver-watch',
      edgeLabel: 'Watch event: new Deployment created',
      what: 'The Deployment Controller inside kube-controller-manager detects the new Deployment resource via an informer watch loop.',
      why: 'Controllers continuously reconcile the observed cluster state with the declared desired state.',
      componentName: 'kube-controller-manager',
      componentRole: 'Runs controller loops that regulate the state of the cluster.',
      docsUrl: 'https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#deployment-controller',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-etcd': 'success',
        'node-apiserver': 'active',
        'node-controllermanager': 'active',
      },
      edgeStatusUpdates: {
        'edge-kubectl-apiserver': 'complete',
        'edge-apiserver-etcd': 'complete',
        'edge-cm-apiserver-watch': 'active',
      },
    },
    {
      stepNumber: 4,
      title: 'Deployment Controller creates underlying ReplicaSet',
      sourceNodeId: 'node-controllermanager',
      targetNodeId: 'node-apiserver',
      edgeId: 'edge-cm-create-rs',
      edgeLabel: `Create ReplicaSet: ${deploymentName}-rs`,
      what: 'The Deployment Controller creates a new ReplicaSet owned by this Deployment with the specified pod template and replica count.',
      why: 'Deployments manage declarative rollouts and versioning by creating and scaling ReplicaSets.',
      componentName: 'kube-controller-manager',
      componentRole: 'Translates high-level Deployment specs into concrete ReplicaSet configurations.',
      docsUrl: 'https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-controllermanager': 'active',
        'node-apiserver': 'active',
      },
      edgeStatusUpdates: {
        'edge-cm-apiserver-watch': 'complete',
        'edge-cm-create-rs': 'active',
      },
    },
    {
      stepNumber: 5,
      title: 'API Server stores ReplicaSet in etcd',
      sourceNodeId: 'node-apiserver',
      targetNodeId: 'node-etcd',
      edgeId: 'edge-apiserver-etcd',
      edgeLabel: `Write /registry/replicasets/.../${deploymentName}-rs`,
      what: 'The API Server validates the ReplicaSet manifest and commits it to the distributed etcd datastore.',
      why: 'etcd provides durable, linearizable storage for the newly created ReplicaSet.',
      componentName: 'etcd',
      componentRole: 'Consistent key-value backing store for all Kubernetes objects.',
      docsUrl: 'https://kubernetes.io/docs/concepts/overview/components/#etcd',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-apiserver': 'active',
        'node-etcd': 'active',
      },
      edgeStatusUpdates: {
        'edge-cm-create-rs': 'complete',
        'edge-apiserver-etcd': 'active',
      },
    },
    {
      stepNumber: 6,
      title: `ReplicaSet Controller creates ${replicas} Pods`,
      sourceNodeId: 'node-controllermanager',
      targetNodeId: 'node-apiserver',
      edgeId: 'edge-cm-create-pods',
      edgeLabel: `Create ${replicas} Pod resources`,
      what: `The ReplicaSet Controller observes that 0 of ${replicas} desired pods exist, and posts ${replicas} new Pod definitions to the API Server.`,
      why: 'The ReplicaSet controller ensures the exact number of pod replicas are running at all times.',
      componentName: 'ReplicaSet Controller',
      componentRole: 'Maintains a stable set of replica Pods running at any given time.',
      docsUrl: 'https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-controllermanager': 'active',
        'node-apiserver': 'active',
      },
      edgeStatusUpdates: {
        'edge-apiserver-etcd': 'complete',
        'edge-cm-create-pods': 'active',
      },
    },
    {
      stepNumber: 7,
      title: `API Server stores ${replicas} Pods in Pending phase`,
      sourceNodeId: 'node-apiserver',
      targetNodeId: 'node-etcd',
      edgeId: 'edge-apiserver-etcd',
      edgeLabel: `Write ${replicas} Pod records (Pending)`,
      what: 'The API Server writes the new Pods to etcd. Since spec.nodeName is unset, all pods enter the Pending state.',
      why: 'Pods must be persisted before the scheduler can evaluate node assignments.',
      componentName: 'kube-apiserver',
      componentRole: 'Persists initial unassigned Pod records.',
      docsUrl: 'https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-apiserver': 'active',
        'node-etcd': 'active',
        [`node-pod-${deploymentName}-1`]: 'warning',
        [`node-pod-${deploymentName}-2`]: 'warning',
        [`node-pod-${deploymentName}-3`]: 'warning',
      },
      edgeStatusUpdates: {
        'edge-cm-create-pods': 'complete',
        'edge-apiserver-etcd': 'active',
      },
    },
    {
      stepNumber: 8,
      title: 'Scheduler evaluates candidate worker nodes',
      sourceNodeId: 'node-scheduler',
      targetNodeId: 'node-apiserver',
      edgeId: 'edge-scheduler-apiserver',
      edgeLabel: 'Filtering and scoring worker nodes',
      what: 'kube-scheduler identifies the unscheduled pods and runs filtering and scoring algorithms across Node 1 and Node 2 to evenly spread replicas.',
      why: 'Spreading pods across multiple worker nodes improves fault tolerance and cluster resource utilization.',
      componentName: 'kube-scheduler',
      componentRole: 'Selects the optimal worker nodes for unscheduled pods.',
      docsUrl: 'https://kubernetes.io/docs/concepts/scheduling-eviction/kube-scheduler/',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-etcd': 'success',
        'node-scheduler': 'active',
        'node-apiserver': 'active',
      },
      edgeStatusUpdates: {
        'edge-apiserver-etcd': 'complete',
        'edge-scheduler-apiserver': 'active',
      },
    },
    {
      stepNumber: 9,
      title: 'Scheduler binds Pods to Worker Nodes in etcd',
      sourceNodeId: 'node-scheduler',
      targetNodeId: 'node-apiserver',
      edgeId: 'edge-scheduler-apiserver',
      edgeLabel: 'Post Bindings: Pod 1 -> Node 1, Pod 2 -> Node 2',
      what: 'The scheduler posts Binding objects to the API Server, setting spec.nodeName for each pod in etcd.',
      why: 'Binding is the explicit assignment of a pod to a specific host machine.',
      componentName: 'kube-scheduler',
      componentRole: 'Commits placement decisions to the cluster state.',
      docsUrl: 'https://kubernetes.io/docs/concepts/scheduling-eviction/kube-scheduler/',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-scheduler': 'success',
        'node-apiserver': 'active',
      },
      edgeStatusUpdates: {
        'edge-scheduler-apiserver': 'active',
      },
    },
    {
      stepNumber: 10,
      title: 'Node Kubelets detect assigned Pods',
      sourceNodeId: 'node-apiserver',
      targetNodeId: 'node-kubelet-1',
      edgeId: 'edge-apiserver-kubelet-1',
      edgeLabel: 'Watch events dispatched to node kubelets',
      what: 'Kubelet on Worker Node 1 and Kubelet on Worker Node 2 receive notifications of pods assigned to their respective nodes.',
      why: 'Each node agent watches for pods bound to its own node name.',
      componentName: 'kubelet',
      componentRole: 'Primary node agent responsible for running pods on the machine.',
      docsUrl: 'https://kubernetes.io/docs/concepts/overview/components/#kubelet',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-apiserver': 'success',
        'node-kubelet-1': 'active',
        'node-kubelet-2': 'active',
      },
      edgeStatusUpdates: {
        'edge-scheduler-apiserver': 'complete',
        'edge-apiserver-kubelet-1': 'active',
        'edge-apiserver-kubelet-2': 'active',
      },
    },
    {
      stepNumber: 11,
      title: 'Container Runtimes pull images and create containers',
      sourceNodeId: 'node-kubelet-1',
      targetNodeId: 'node-containerruntime-1',
      edgeId: 'edge-kubelet-runtime-1',
      edgeLabel: 'CRI: PullImage & CreateContainer',
      what: 'The Kubelets communicate with local Container Runtimes (containerd) over CRI gRPC to fetch container images and create network sandboxes.',
      why: 'Container runtimes execute the container processes in isolated namespaces on host nodes.',
      componentName: 'Container Runtime',
      componentRole: 'Pulls container images and executes processes inside sandboxes.',
      docsUrl: 'https://kubernetes.io/docs/concepts/overview/components/#container-runtime',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-containerruntime-1': 'active',
        'node-containerruntime-2': 'active',
      },
      edgeStatusUpdates: {
        'edge-apiserver-kubelet-1': 'complete',
        'edge-apiserver-kubelet-2': 'complete',
        'edge-kubelet-runtime-1': 'active',
        'edge-kubelet-runtime-2': 'active',
      },
    },
    {
      stepNumber: 12,
      title: 'All Pods enter Running phase, Deployment is Ready',
      sourceNodeId: 'node-containerruntime-1',
      targetNodeId: `node-pod-${deploymentName}-1`,
      edgeId: 'edge-runtime-pods-1',
      edgeLabel: 'Status: Running & Ready',
      what: `All ${replicas} containers start successfully. Kubelets report pod status as Running to the API Server, and the Deployment marks ${replicas}/${replicas} replicas ready.`,
      why: 'The desired state declared in the manifest now matches the live cluster state.',
      componentName: 'Deployment Workload',
      componentRole: 'Provides declarative updates for Pods and ReplicaSets.',
      docsUrl: 'https://kubernetes.io/docs/concepts/workloads/controllers/deployment/',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-containerruntime-1': 'success',
        'node-containerruntime-2': 'success',
        'node-kubelet-1': 'success',
        'node-kubelet-2': 'success',
        'node-controllermanager': 'success',
        [`node-pod-${deploymentName}-1`]: 'success',
        [`node-pod-${deploymentName}-2`]: 'success',
        [`node-pod-${deploymentName}-3`]: 'success',
      },
      edgeStatusUpdates: {
        'edge-kubelet-runtime-1': 'complete',
        'edge-kubelet-runtime-2': 'complete',
        'edge-runtime-pods-1': 'active',
        'edge-runtime-pods-2': 'active',
      },
    },
  ];
}
