import { LifecycleStep } from '../model/types.ts';

export function createIngressLifecycleSteps(
  ingressName = 'web-ingress',
  host = 'app.example.com',
  path = '/',
  serviceName = 'web-service',
): LifecycleStep[] {
  return [
    {
      stepNumber: 1,
      title: 'kubectl submits Ingress manifest',
      sourceNodeId: 'node-external-client',
      targetNodeId: 'node-kubectl',
      edgeId: 'edge-user-kubectl',
      edgeLabel: `kubectl apply -f ${ingressName}.yaml`,
      what: 'The developer applies the Ingress manifest. kubectl translates the YAML into an API request and submits it to kube-apiserver.',
      why: 'Ingress objects define external HTTP/HTTPS routing rules into cluster services.',
      componentName: 'kubectl',
      componentRole: 'CLI client submitting Ingress configuration.',
      docsUrl: 'https://kubernetes.io/docs/concepts/services-networking/ingress/',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-external-client': 'success',
        'node-kubectl': 'active',
      },
      edgeStatusUpdates: {
        'edge-user-kubectl': 'active',
      },
    },
    {
      stepNumber: 2,
      title: 'API Server validates and stores Ingress',
      sourceNodeId: 'node-kubectl',
      targetNodeId: 'node-apiserver',
      edgeId: 'edge-kubectl-apiserver',
      edgeLabel: 'POST /apis/networking.k8s.io/v1/ingresses',
      what: 'kube-apiserver validates hostnames, path definitions, and backend service targets before writing the Ingress record to etcd.',
      why: 'Centralized validation prevents malformed routing configurations from reaching controllers.',
      componentName: 'kube-apiserver',
      componentRole: 'Validates and persists Ingress definitions.',
      docsUrl: 'https://kubernetes.io/docs/concepts/overview/components/#kube-apiserver',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-kubectl': 'success',
        'node-apiserver': 'active',
        'node-etcd': 'active',
      },
      edgeStatusUpdates: {
        'edge-user-kubectl': 'complete',
        'edge-kubectl-apiserver': 'active',
        'edge-apiserver-etcd': 'active',
      },
    },
    {
      stepNumber: 3,
      title: 'Ingress Controller watches Ingress updates',
      sourceNodeId: 'node-ingress-controller',
      targetNodeId: 'node-apiserver',
      edgeId: 'edge-ic-apiserver-watch',
      edgeLabel: 'Watch event: new Ingress object added',
      what: 'The Ingress Controller (such as ingress-nginx or Envoy Gateway) detects the newly created Ingress resource through its continuous watch channel.',
      why: 'An Ingress resource requires a running Ingress Controller in the cluster to satisfy declared routing rules.',
      componentName: 'Ingress Controller',
      componentRole: 'Application proxy implementing the Ingress specification.',
      docsUrl: 'https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-etcd': 'success',
        'node-ingress-controller': 'active',
        'node-apiserver': 'active',
      },
      edgeStatusUpdates: {
        'edge-kubectl-apiserver': 'complete',
        'edge-apiserver-etcd': 'complete',
        'edge-ic-apiserver-watch': 'active',
      },
    },
    {
      stepNumber: 4,
      title: `Ingress Controller parses routing rules (${host}${path})`,
      sourceNodeId: 'node-ingress-controller',
      targetNodeId: `node-ingress-${ingressName}`,
      edgeId: 'edge-ic-update-rules',
      edgeLabel: `Parse rules: ${host}${path} -> ${serviceName}:80`,
      what: `The Ingress Controller reads the host header (${host}) and URL path prefix (${path}) targeting backend service ${serviceName}.`,
      why: 'Path-based and host-based routing allows multiple applications to share a single public IP address.',
      componentName: 'Ingress Controller',
      componentRole: 'Translates Kubernetes ingress rules into proxy routing tables.',
      docsUrl: 'https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-rules',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-ingress-controller': 'active',
        [`node-ingress-${ingressName}`]: 'active',
      },
      edgeStatusUpdates: {
        'edge-ic-apiserver-watch': 'complete',
        'edge-ic-update-rules': 'active',
      },
    },
    {
      stepNumber: 5,
      title: 'Ingress Controller reloads proxy configuration',
      sourceNodeId: 'node-ingress-controller',
      targetNodeId: `node-ingress-${ingressName}`,
      edgeId: 'edge-ic-update-rules',
      edgeLabel: 'Dynamic reload: proxy upstream configured',
      what: 'The Ingress Controller dynamically updates its internal routing table or reloads nginx without dropping active client connections.',
      why: 'Dynamic configuration updates allow zero-downtime routing modifications.',
      componentName: 'Ingress Controller',
      componentRole: 'Applies updated routing policies to active proxy workers.',
      docsUrl: 'https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-ingress-controller': 'success',
        [`node-ingress-${ingressName}`]: 'success',
      },
      edgeStatusUpdates: {
        'edge-ic-update-rules': 'complete',
      },
    },
    {
      stepNumber: 6,
      title: 'External client sends HTTP request',
      sourceNodeId: 'node-external-client',
      targetNodeId: 'node-ingress-controller',
      edgeId: 'edge-client-ic-request',
      edgeLabel: `GET http://${host}${path}`,
      what: `A user or client on the public internet sends an HTTP request with Host header "${host}" to the public Ingress IP address.`,
      why: 'Ingress acts as the single edge entry point, terminating client connections at the cluster boundary.',
      componentName: 'External Client',
      componentRole: 'Internet client sending HTTP traffic.',
      docsUrl: 'https://kubernetes.io/docs/concepts/services-networking/ingress/',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-external-client': 'active',
        'node-ingress-controller': 'active',
      },
      edgeStatusUpdates: {
        'edge-client-ic-request': 'active',
      },
    },
    {
      stepNumber: 7,
      title: 'Ingress Controller matches Host and Path headers',
      sourceNodeId: 'node-ingress-controller',
      targetNodeId: `node-ingress-${ingressName}`,
      edgeId: 'edge-ic-update-rules',
      edgeLabel: `Match Host: ${host}, Path: ${path}`,
      what: `The Ingress Controller inspects the incoming request, matching the Host header against "${host}" and the URI against "${path}".`,
      why: 'Header inspection determines which backend Kubernetes service should receive the request.',
      componentName: 'Ingress Controller',
      componentRole: 'Evaluates HTTP headers against registered routing rules.',
      docsUrl: 'https://kubernetes.io/docs/concepts/services-networking/ingress/#name-based-virtual-hosting',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-ingress-controller': 'active',
      },
      edgeStatusUpdates: {
        'edge-client-ic-request': 'complete',
      },
    },
    {
      stepNumber: 8,
      title: `Ingress Controller resolves backend Service (${serviceName})`,
      sourceNodeId: 'node-ingress-controller',
      targetNodeId: `node-service-${serviceName}`,
      edgeId: 'edge-ic-service-lookup',
      edgeLabel: `Lookup Endpoints for ${serviceName}`,
      what: `The Ingress Controller looks up the Endpoints for service "${serviceName}" to obtain active backend pod IP addresses directly.`,
      why: 'Most modern Ingress Controllers bypass kube-proxy and route directly to backend pod IPs to reduce network latency.',
      componentName: 'Ingress Controller',
      componentRole: 'Direct endpoint resolution for high-performance proxying.',
      docsUrl: 'https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-ingress-controller': 'active',
        [`node-service-${serviceName}`]: 'active',
      },
      edgeStatusUpdates: {
        'edge-ic-service-lookup': 'active',
      },
    },
    {
      stepNumber: 9,
      title: 'Ingress Controller proxies request directly to Pod',
      sourceNodeId: 'node-ingress-controller',
      targetNodeId: `node-pod-${serviceName}-backend`,
      edgeId: 'edge-ic-proxy-pod',
      edgeLabel: 'TCP proxy -> 10.244.1.20:8080',
      what: 'The Ingress Controller establishes a connection to the selected healthy pod IP (10.244.1.20:8080) and forwards the HTTP request.',
      why: 'Direct pod routing avoids unnecessary extra hops through node iptables tables.',
      componentName: 'Ingress Controller',
      componentRole: 'Forwards request payload to target container socket.',
      docsUrl: 'https://kubernetes.io/docs/concepts/services-networking/ingress/',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-ingress-controller': 'active',
        [`node-service-${serviceName}`]: 'success',
        [`node-pod-${serviceName}-backend`]: 'active',
      },
      edgeStatusUpdates: {
        'edge-ic-service-lookup': 'complete',
        'edge-ic-proxy-pod': 'active',
      },
    },
    {
      stepNumber: 10,
      title: 'Pod processes request and returns HTTP response',
      sourceNodeId: `node-pod-${serviceName}-backend`,
      targetNodeId: 'node-ingress-controller',
      edgeId: 'edge-pod-ic-response',
      edgeLabel: 'HTTP 200 OK (Pod response)',
      what: 'The application container processes the HTTP request and sends an HTTP 200 OK response back to the Ingress Controller.',
      why: 'The container business logic fulfills the client request.',
      componentName: 'Backend Pod',
      componentRole: 'Runs application logic and generates responses.',
      docsUrl: 'https://kubernetes.io/docs/concepts/workloads/pods/',
      durationMs: 2000,
      nodeStatusUpdates: {
        [`node-pod-${serviceName}-backend`]: 'success',
        'node-ingress-controller': 'active',
      },
      edgeStatusUpdates: {
        'edge-ic-proxy-pod': 'complete',
        'edge-pod-ic-response': 'active',
      },
    },
    {
      stepNumber: 11,
      title: 'Ingress Controller forwards response to external client',
      sourceNodeId: 'node-ingress-controller',
      targetNodeId: 'node-external-client',
      edgeId: 'edge-ic-client-response',
      edgeLabel: 'HTTP 200 OK (Completed)',
      what: 'The Ingress Controller streams the HTTP response back to the client over the public internet connection.',
      why: 'Completes the end-to-end client request lifecycle from internet edge to pod and back.',
      componentName: 'Ingress Controller',
      componentRole: 'Delivers response to the initiating client.',
      docsUrl: 'https://kubernetes.io/docs/concepts/services-networking/ingress/',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-ingress-controller': 'success',
        'node-external-client': 'success',
      },
      edgeStatusUpdates: {
        'edge-pod-ic-response': 'complete',
        'edge-ic-client-response': 'active',
      },
    },
  ];
}
