import { LifecycleStep } from '../model/types.ts';

export function createPodLifecycleSteps(podName = 'nginx-pod'): LifecycleStep[] {
  const podNodeId = `node-pod-${podName}`;

  return [
    {
      stepNumber: 1,
      title: 'kubectl submits manifest',
      sourceNodeId: 'node-user',
      targetNodeId: 'node-kubectl',
      edgeId: 'edge-user-kubectl',
      edgeLabel: `kubectl apply -f ${podName}.yaml`,
      what: 'The developer runs kubectl apply. The kubectl CLI parses the YAML manifest locally and constructs an HTTP request.',
      why: 'kubectl acts as the client communicating with the Kubernetes cluster control plane.',
      componentName: 'kubectl',
      componentRole: 'Command-line tool for communicating with the cluster API server.',
      docsUrl: 'https://kubernetes.io/docs/reference/kubectl/',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-user': 'success',
        'node-kubectl': 'active',
      },
      edgeStatusUpdates: {
        'edge-user-kubectl': 'active',
      },
    },
    {
      stepNumber: 2,
      title: 'API Server receives and validates manifest',
      sourceNodeId: 'node-kubectl',
      targetNodeId: 'node-apiserver',
      edgeId: 'edge-kubectl-apiserver',
      edgeLabel: 'POST /api/v1/namespaces/default/pods',
      what: 'The API Server authenticates the user, authorizes the request, and passes the Pod manifest through mutating and validating admission webhooks.',
      why: 'kube-apiserver is the single point of entry to the cluster, ensuring all resource requests are validated before persisting.',
      componentName: 'kube-apiserver',
      componentRole: 'Validates and configures data for pods, services, replication controllers, and others.',
      docsUrl: 'https://kubernetes.io/docs/concepts/overview/components/#kube-apiserver',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-kubectl': 'success',
        'node-apiserver': 'active',
      },
      edgeStatusUpdates: {
        'edge-user-kubectl': 'complete',
        'edge-kubectl-apiserver': 'active',
      },
    },
    {
      stepNumber: 3,
      title: 'API Server stores Pod spec in etcd',
      sourceNodeId: 'node-apiserver',
      targetNodeId: 'node-etcd',
      edgeId: 'edge-apiserver-etcd',
      edgeLabel: `Write /registry/pods/default/${podName}`,
      what: 'The API Server writes the validated Pod definition into etcd. The Pod enters the Pending phase with no node assigned yet.',
      why: 'etcd is the consistent and highly-available key-value store for all cluster state.',
      componentName: 'etcd',
      componentRole: 'Consistent and highly-available key value store used as Kubernetes backing store.',
      docsUrl: 'https://kubernetes.io/docs/concepts/overview/components/#etcd',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-apiserver': 'active',
        'node-etcd': 'active',
        [podNodeId]: 'warning',
      },
      edgeStatusUpdates: {
        'edge-kubectl-apiserver': 'complete',
        'edge-apiserver-etcd': 'active',
      },
    },
    {
      stepNumber: 4,
      title: 'Scheduler detects unscheduled Pod',
      sourceNodeId: 'node-scheduler',
      targetNodeId: 'node-apiserver',
      edgeId: 'edge-scheduler-apiserver-watch',
      edgeLabel: 'Watch event: new unscheduled Pod',
      what: 'The Scheduler constantly watches the API Server for pods with spec.nodeName unset and filters candidate nodes based on resource requests and affinity.',
      why: 'Decoupled scheduling allows pluggable policies and independent scaling of cluster control plane components.',
      componentName: 'kube-scheduler',
      componentRole: 'Watches for newly created Pods with no assigned node and selects a node for them.',
      docsUrl: 'https://kubernetes.io/docs/concepts/scheduling-eviction/kube-scheduler/',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-etcd': 'success',
        'node-scheduler': 'active',
        'node-apiserver': 'active',
      },
      edgeStatusUpdates: {
        'edge-apiserver-etcd': 'complete',
        'edge-scheduler-apiserver-watch': 'active',
      },
    },
    {
      stepNumber: 5,
      title: 'Scheduler assigns Pod to Worker Node',
      sourceNodeId: 'node-scheduler',
      targetNodeId: 'node-apiserver',
      edgeId: 'edge-scheduler-apiserver-bind',
      edgeLabel: `Create Binding: ${podName} -> node-1`,
      what: 'The Scheduler chooses Worker Node 1 and posts a Binding object back to the API Server. The API Server updates the Pod record in etcd.',
      why: 'Assigning a node updates spec.nodeName, signaling the node Kubelet to initiate container startup.',
      componentName: 'kube-scheduler',
      componentRole: 'Scores available worker nodes and binds the pod to the best match.',
      docsUrl: 'https://kubernetes.io/docs/concepts/scheduling-eviction/kube-scheduler/',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-scheduler': 'success',
        'node-apiserver': 'active',
      },
      edgeStatusUpdates: {
        'edge-scheduler-apiserver-watch': 'complete',
        'edge-scheduler-apiserver-bind': 'active',
      },
    },
    {
      stepNumber: 6,
      title: 'Kubelet receives Pod assignment',
      sourceNodeId: 'node-apiserver',
      targetNodeId: 'node-kubelet',
      edgeId: 'edge-apiserver-kubelet',
      edgeLabel: `Watch event: Pod assigned to node-1`,
      what: 'The Kubelet on Worker Node 1 observes the Pod assigned to its node via its watch connection to the API Server.',
      why: 'Kubelet is the primary node agent responsible for maintaining pod lifecycle on the host.',
      componentName: 'kubelet',
      componentRole: 'An agent that runs on each node in the cluster ensuring containers are running in a Pod.',
      docsUrl: 'https://kubernetes.io/docs/concepts/overview/components/#kubelet',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-apiserver': 'success',
        'node-kubelet': 'active',
      },
      edgeStatusUpdates: {
        'edge-scheduler-apiserver-bind': 'complete',
        'edge-apiserver-kubelet': 'active',
      },
    },
    {
      stepNumber: 7,
      title: 'Kubelet requests container pull and creation',
      sourceNodeId: 'node-kubelet',
      targetNodeId: 'node-containerruntime',
      edgeId: 'edge-kubelet-runtime',
      edgeLabel: 'CRI: PullImage & RunPodSandbox',
      what: 'Kubelet calls the Container Runtime Interface (CRI) over gRPC to pull container images, set up Linux network namespaces, and create containers.',
      why: 'The Container Runtime Interface standardizes how Kubernetes interacts with runtimes like containerd and CRI-O.',
      componentName: 'Container Runtime',
      componentRole: 'The software responsible for pulling images and running containers (containerd, CRI-O).',
      docsUrl: 'https://kubernetes.io/docs/concepts/overview/components/#container-runtime',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-kubelet': 'active',
        'node-containerruntime': 'active',
      },
      edgeStatusUpdates: {
        'edge-apiserver-kubelet': 'complete',
        'edge-kubelet-runtime': 'active',
      },
    },
    {
      stepNumber: 8,
      title: 'Containers start and Pod enters Running phase',
      sourceNodeId: 'node-containerruntime',
      targetNodeId: podNodeId,
      edgeId: 'edge-runtime-pod',
      edgeLabel: 'StartContainer: status -> Running',
      what: 'The container runtime starts the application process inside the pod sandbox. Kubelet reports the status back to API Server as Running.',
      why: 'A running status confirms that all containers inside the pod have initialized without immediate failure.',
      componentName: 'Pod Workload',
      componentRole: 'The smallest deployable computing unit that can be created and managed in Kubernetes.',
      docsUrl: 'https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-containerruntime': 'success',
        'node-kubelet': 'success',
        [podNodeId]: 'success',
      },
      edgeStatusUpdates: {
        'edge-kubelet-runtime': 'complete',
        'edge-runtime-pod': 'active',
      },
    },
    {
      stepNumber: 9,
      title: 'kube-proxy updates node network rules',
      sourceNodeId: 'node-kubeproxy',
      targetNodeId: podNodeId,
      edgeId: 'edge-proxy-pod',
      edgeLabel: 'iptables / IPVS rule updated',
      what: 'kube-proxy updates local packet forwarding rules (iptables or IPVS) so traffic directed to the pod IP or relevant service can be routed properly.',
      why: 'kube-proxy maintains network rules on nodes allowing network communication to your Pods from inside or outside the cluster.',
      componentName: 'kube-proxy',
      componentRole: 'Maintains network rules on nodes allowing communication to Pods from cluster sessions.',
      docsUrl: 'https://kubernetes.io/docs/concepts/overview/components/#kube-proxy',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-kubeproxy': 'success',
        [podNodeId]: 'success',
      },
      edgeStatusUpdates: {
        'edge-runtime-pod': 'complete',
        'edge-proxy-pod': 'active',
      },
    },
  ];
}
