import { LifecycleStep } from '../model/types.ts';

export function createServiceLifecycleSteps(
  serviceName = 'backend-service',
  serviceType = 'ClusterIP',
  clusterIP = '10.96.0.42',
): LifecycleStep[] {
  return [
    {
      stepNumber: 1,
      title: 'kubectl submits Service manifest',
      sourceNodeId: 'node-user',
      targetNodeId: 'node-kubectl',
      edgeId: 'edge-user-kubectl',
      edgeLabel: `kubectl apply -f ${serviceName}.yaml`,
      what: 'The developer applies the Service definition. kubectl validates the manifest locally and submits a POST request to kube-apiserver.',
      why: 'Services provide stable network endpoints for dynamic sets of pods.',
      componentName: 'kubectl',
      componentRole: 'CLI client submitting the Service configuration.',
      docsUrl: 'https://kubernetes.io/docs/concepts/services-networking/service/',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-user': 'success',
        'node-kubectl': 'active',
      },
      edgeStatusUpdates: {
        'edge-user-kubectl': 'active',
      },
    },
    {
      stepNumber: 2,
      title: 'API Server validates Service object',
      sourceNodeId: 'node-kubectl',
      targetNodeId: 'node-apiserver',
      edgeId: 'edge-kubectl-apiserver',
      edgeLabel: 'POST /api/v1/services',
      what: 'The API Server verifies that the service name, ports, and selectors adhere to Kubernetes networking specifications.',
      why: 'Validating ensures port definitions (port and targetPort) are correctly structured before allocating cluster resources.',
      componentName: 'kube-apiserver',
      componentRole: 'Validates and accepts API requests for services.',
      docsUrl: 'https://kubernetes.io/docs/concepts/overview/components/#kube-apiserver',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-kubectl': 'success',
        'node-apiserver': 'active',
      },
      edgeStatusUpdates: {
        'edge-user-kubectl': 'complete',
        'edge-kubectl-apiserver': 'active',
      },
    },
    {
      stepNumber: 3,
      title: `API Server allocates ClusterIP (${clusterIP})`,
      sourceNodeId: 'node-apiserver',
      targetNodeId: 'node-etcd',
      edgeId: 'edge-apiserver-etcd',
      edgeLabel: `Allocate ClusterIP: ${clusterIP}`,
      what: `kube-apiserver draws an available virtual IP address (${clusterIP}) from the configured service-cluster-ip-range CIDR block and commits the Service record to etcd.`,
      why: 'ClusterIP is a stable virtual IP address that remains constant across pod restarts and rescheduling.',
      componentName: 'kube-apiserver',
      componentRole: 'Manages cluster IP address pool allocation.',
      docsUrl: 'https://kubernetes.io/docs/concepts/services-networking/service/#type-clusterip',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-apiserver': 'active',
        'node-etcd': 'active',
        [`node-service-${serviceName}`]: 'active',
      },
      edgeStatusUpdates: {
        'edge-kubectl-apiserver': 'complete',
        'edge-apiserver-etcd': 'active',
      },
    },
    {
      stepNumber: 4,
      title: 'EndpointSlice Controller matches Pod selectors',
      sourceNodeId: 'node-controllermanager',
      targetNodeId: 'node-apiserver',
      edgeId: 'edge-cm-ep-controller',
      edgeLabel: 'Watch: match Service selector with healthy Pods',
      what: 'The EndpointSlice Controller in kube-controller-manager detects the Service and scans existing pods in the namespace matching the label selector.',
      why: 'Decoupled endpoint tracking enables high scalability when managing thousands of backend pods.',
      componentName: 'EndpointSlice Controller',
      componentRole: 'Tracks healthy backend pods matching Service selectors.',
      docsUrl: 'https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-etcd': 'success',
        'node-controllermanager': 'active',
        'node-apiserver': 'active',
      },
      edgeStatusUpdates: {
        'edge-apiserver-etcd': 'complete',
        'edge-cm-ep-controller': 'active',
      },
    },
    {
      stepNumber: 5,
      title: 'EndpointSlice Controller creates EndpointSlice record',
      sourceNodeId: 'node-controllermanager',
      targetNodeId: `node-endpointslice-${serviceName}`,
      edgeId: 'edge-cm-create-epslice',
      edgeLabel: 'Generate EndpointSlice with Pod IPs [10.244.1.5, 10.244.2.8]',
      what: 'The controller creates an EndpointSlice containing the IP addresses, readiness states, and ports of matched target pods.',
      why: 'EndpointSlices group endpoints into chunks of up to 100 entries, avoiding massive single Endpoint objects.',
      componentName: 'EndpointSlice Controller',
      componentRole: 'Publishes scalable chunks of network endpoints.',
      docsUrl: 'https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-controllermanager': 'active',
        [`node-endpointslice-${serviceName}`]: 'active',
      },
      edgeStatusUpdates: {
        'edge-cm-ep-controller': 'complete',
        'edge-cm-create-epslice': 'active',
      },
    },
    {
      stepNumber: 6,
      title: 'API Server persists EndpointSlice in etcd',
      sourceNodeId: 'node-apiserver',
      targetNodeId: 'node-etcd',
      edgeId: 'edge-apiserver-etcd',
      edgeLabel: `Write /registry/endpointslices/.../${serviceName}`,
      what: 'The API Server commits the EndpointSlice object to etcd and broadcasts notification events to all active watchers.',
      why: 'Broadcasting watch events informs node proxies of updated endpoint routing destinations.',
      componentName: 'kube-apiserver',
      componentRole: 'Persists and fans out EndpointSlice updates.',
      docsUrl: 'https://kubernetes.io/docs/concepts/overview/components/#etcd',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-apiserver': 'active',
        'node-etcd': 'active',
        [`node-endpointslice-${serviceName}`]: 'success',
      },
      edgeStatusUpdates: {
        'edge-cm-create-epslice': 'complete',
        'edge-apiserver-etcd': 'active',
      },
    },
    {
      stepNumber: 7,
      title: 'kube-proxy on Worker Nodes detects EndpointSlice',
      sourceNodeId: 'node-apiserver',
      targetNodeId: 'node-kubeproxy-1',
      edgeId: 'edge-apiserver-proxy-1',
      edgeLabel: 'EndpointSlice update streamed to kube-proxy',
      what: 'kube-proxy instances running on Worker Node 1 and Worker Node 2 receive the new EndpointSlice via their long-lived API Server watch channels.',
      why: 'kube-proxy synchronizes network tables on each node to ensure seamless East-West traffic distribution.',
      componentName: 'kube-proxy',
      componentRole: 'Node proxy maintaining local packet forwarding rules.',
      docsUrl: 'https://kubernetes.io/docs/concepts/overview/components/#kube-proxy',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-etcd': 'success',
        'node-kubeproxy-1': 'active',
        'node-kubeproxy-2': 'active',
      },
      edgeStatusUpdates: {
        'edge-apiserver-etcd': 'complete',
        'edge-apiserver-proxy-1': 'active',
        'edge-apiserver-proxy-2': 'active',
      },
    },
    {
      stepNumber: 8,
      title: 'kube-proxy installs packet forwarding rules (iptables/IPVS)',
      sourceNodeId: 'node-kubeproxy-1',
      targetNodeId: 'node-pod-backend-1',
      edgeId: 'edge-proxy-rules-1',
      edgeLabel: `DNAT rule: ${clusterIP}:80 -> [10.244.1.5:8080, 10.244.2.8:8080]`,
      what: `kube-proxy programs the Linux kernel netfilter tables with random probability distribution, load balancing traffic destined for ${clusterIP} across all healthy backend pods.`,
      why: 'Kernel-level routing delivers high-performance load balancing without requiring an in-path userspace proxy.',
      componentName: 'kube-proxy',
      componentRole: 'Programs kernel packet filtering and NAT table entries.',
      docsUrl: 'https://kubernetes.io/docs/reference/networking/virtual-ips/',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-kubeproxy-1': 'success',
        'node-kubeproxy-2': 'success',
        'node-pod-backend-1': 'success',
        'node-pod-backend-2': 'success',
      },
      edgeStatusUpdates: {
        'edge-apiserver-proxy-1': 'complete',
        'edge-apiserver-proxy-2': 'complete',
        'edge-proxy-rules-1': 'active',
        'edge-proxy-rules-2': 'active',
      },
    },
    {
      stepNumber: 9,
      title: 'CoreDNS registers internal DNS record',
      sourceNodeId: 'node-coredns',
      targetNodeId: 'node-apiserver',
      edgeId: 'edge-coredns-watch',
      edgeLabel: `Create A Record: ${serviceName}.default.svc.cluster.local -> ${clusterIP}`,
      what: `CoreDNS observes the new Service and registers an authoritative DNS A record pointing ${serviceName}.default.svc.cluster.local to ${clusterIP}.`,
      why: 'DNS-based service discovery allows pods to connect to services by name without hardcoding IP addresses.',
      componentName: 'CoreDNS',
      componentRole: 'Cluster DNS server providing name resolution for Kubernetes services.',
      docsUrl: 'https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/',
      durationMs: 2000,
      nodeStatusUpdates: {
        'node-coredns': 'success',
      },
      edgeStatusUpdates: {
        'edge-proxy-rules-1': 'complete',
        'edge-proxy-rules-2': 'complete',
        'edge-coredns-watch': 'active',
      },
    },
    {
      stepNumber: 10,
      title: 'Service is fully active and routable',
      sourceNodeId: `node-service-${serviceName}`,
      targetNodeId: `node-endpointslice-${serviceName}`,
      edgeId: 'edge-service-epslice',
      edgeLabel: `Service Ready: ${serviceType} (${clusterIP}:80)`,
      what: `The Service is active. Any pod in the cluster can now send traffic to ${serviceName} or ${clusterIP}:80 and be transparently routed to healthy backend containers.`,
      why: 'The service abstraction decouples frontend clients from changing backend pod lifecycles and IP addresses.',
      componentName: 'Service Networking',
      componentRole: 'Abstract way to expose an application running on a set of Pods.',
      docsUrl: 'https://kubernetes.io/docs/concepts/services-networking/service/',
      durationMs: 2000,
      nodeStatusUpdates: {
        [`node-service-${serviceName}`]: 'success',
        [`node-endpointslice-${serviceName}`]: 'success',
      },
      edgeStatusUpdates: {
        'edge-coredns-watch': 'complete',
        'edge-service-epslice': 'active',
      },
    },
  ];
}
